### ISSUE TITLE
Cannot destructure property 'request_id' of 'response' as it is undefined

### ISSUE THREAD

**Issue by thomasa88** [huggingface/llm-vscode#109]
I just installed llm-vscode and did "Llm: Login" using my hugging face token (read-only).

When I try "Llm: After Insert" (which I assume is the completion command), I get an error message dialog:

> **Command 'Llm: After Insert' resulted in an error**
> Cannot destructure property 'request_id' of 'response' as it is undefined.

VS code version: 1.84.1
OS: Ubuntu 23.10
llm-vscode: 0.1.6

I have tried with starcoder and codellma as Config Template.

**Comment by Kaschi14** [comment]
If that is not the completion command, what is? I would like to trigger it manually as sometimes my llm response time is very low and I want to make sure that it actually triggerred. I feel like llm-vscode sometimes does not trigger automatically

**Comment by McPatate** [comment]
> Completion is currently bound to the following keybinding:
>
>      {
>        "key": "cmd+shift+l",
>        "command": "editor.action.inlineSuggest.trigger"
>      },
