### ISSUE TITLE
Extension causes code-oss to crash

### ISSUE THREAD

**Issue by frost19k** [huggingface/llm-vscode#110]
```
┌──(hoodly㉿kali-vm)-[~]
└─$ code-oss      
[main 2023-11-27T03:27:18.240Z] update#setState disabled
[main 2023-11-27T03:27:18.241Z] update#ctor - updates are disabled as there is no update URL
[1]    300135 segmentation fault  code-oss
```

This happens either when you try to login or when the extension fetches completions from the model.

I'm not quite sophisticated enough to get you a stack trace :(

Version: 1.82.2
Commit: Unknown
Date: 2023-10-03T19:02:33.150Z
Electron: 25.8.1
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-kali3-amd64

**Comment by McPatate** [comment]
Are you still facing issues with `0.2.x` ?
