### ISSUE TITLE
Sending custom header with each API request

### ISSUE THREAD

**Issue by Simon-Stone** [huggingface/llm-vscode#114]
Can I add custom headers to the API requests? This would be very helpful for authentication purposes.

**Comment by McPatate** [comment]
Currently not possible, is Bearer Auth not what you're looking for?

**Comment by Simon-Stone** [comment]
That is what I'm looking for. Is that an option already? Did I miss it?

**Comment by Simon-Stone** [comment]
@McPatate Could you point me in the right direction how to use `Bearer Auth` for this?

**Comment by McPatate** [comment]
I'll close this for now, feel free to re-open if your issue persists.
