### ISSUE TITLE
[BUG] Crash on new untitled VS Code file

### ISSUE THREAD

**Issue by DataOps7** [huggingface/llm-vscode#119]
### Bug

To reproduce:

* Press `Ctrl + n`  in VS Code
* Start typing

The LLM LS crashes on every completion,
After 5 crashes it doesn't restart, which makes the extension unusable.

### Temporary fix

Add the following code snippet to the provider's `provideInlineCompletionItems` method:

```typescript
if (document.isUntitled) {
    return;
}
``` 

This will deactivate the extension on new untitled documents which would save you from crashes,
until the error is properly fixed in the llm-ls.

**Comment by McPatate** [comment]
Is this still an issue ?
