### ISSUE TITLE
[BUG] Continuous file change events

### ISSUE THREAD

**Issue by pip25** [huggingface/llm-vscode#120]
VSCode version: 1.85.1

In the output of the extension, I see a continuous stream of messages like this:

`2024-01-18 13:06:07.542 [info] [Info  - 1:06:07 PM] {llm-ls} file changed`

About 4 messages are added every second, even when the IDE is completely idle. I have no proof, but I suspect that at least some of these events results in LLM queries, because I reach the rate limit suspiciously quickly for my HuggingFace account.

**Comment by DanielAdari** [comment]
Can approve,
I'm getting the same output.

**Comment by HennerM** [comment]
I identified the bug, it's because we get change events from the `output` channel which in turn creates more because we also write to the output ourselves, see https://github.com/huggingface/llm-ls/pull/59 for the fix
