### ISSUE TITLE
Latest version is crashing when using autocomplete

### ISSUE THREAD

**Issue by darolt** [huggingface/llm-vscode#121]
I am using this extension on a private model. It works fine in version v0.1.0. However it does not work in v0.1.6.
When typing I get a pop-up with this message:
`Pending response rejected since connection got disposed`
In the output the logs show:

```
2024-01-19 10:28:34.333 [info] thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.0/src/rope.rs:803:13:
Attempt to index past end of Rope: char index 155, Rope char length 155
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-19 10:28:34.334 [info] [Info  - 10:28:34 AM] {llm-ls} file changed
```
Apparently the error occurs only when the cursor is at the end of the file. In other positions, it seems to work.

After 5 attempts, it gives the following message:
`The LLM VS Code server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

For runtime status, it seems ok:
![image](https://github.com/huggingface/llm-vscode/assets/16036931/4a8ae2ff-c2e3-4a49-ac4c-31b47edd1831)

The VS Code details:
![image](https://github.com/huggingface/llm-vscode/assets/16036931/37edc261-6096-4592-a6ac-abe2003117b4)

**Comment by McPatate** [comment]
Does upgrading in `0.2.x` fix the issue?
