### ISSUE TITLE
Support for Llamacpp

### ISSUE THREAD

**Issue by FredericoPerimLopes** [huggingface/llm-vscode#132]
@McPatate I have made some adjustments to enable 
LlamaCpp support. It seems to be working, do you think this would be something useful?

**Comment by McPatate** [comment]
Feel free to open a PR :)

**Comment by FredericoPerimLopes** [comment]
I have also pushed one in the llm-ls repo.

**Comment by McPatate** [comment]
Linked to: https://github.com/huggingface/llm-ls/pull/81

**Comment by McPatate** [comment]
https://github.com/huggingface/llm-ls/pull/94 has just been merged, should be available in llm-vscode soon once I release
