### ISSUE TITLE
BUG: LLM-vscode breaks core VSCode keybindings

### ISSUE THREAD

**Issue by FrenchBen** [huggingface/llm-vscode#138]
_surprised that no issue has been created for this_

`cmd+shift+L` is one of the core bindings for VSCode, allowing a user to quickly "Select all occurrences of current selection" via `editor.action.selectHighlights` ref: https://code.visualstudio.com/docs/getstarted/keybindings

Why is llm-vscode overriding this thus breaking a core function?
https://github.com/huggingface/llm-vscode/blob/c9e1faf559ccd5b9d3a26f68fc54b35fd5cfa509/package.json#L229
```
{
  "key": "cmd+shift+l",
  "command": "editor.action.inlineSuggest.trigger"
},
```

If the same keybinding is to be preserved, I would suggest adding some context: https://code.visualstudio.com/api/references/when-clause-contexts

**Comment by McPatate** [comment]
Hello, I had no idea this binding was used for something else, this shortcut is a legacy shortcut from the previous extension. You can always change it if it doesn't suit you.
I'll check to change the value to something that doesn't conflict when I have some time.

**Comment by FrenchBen** [comment]
Updated the code to use a less-common shortcut, and still preserve the original VSCode one.
