### ISSUE TITLE
Alternative plugin for Jetbrains IntelliJ?

### ISSUE THREAD

**Issue by alexmensak** [huggingface/llm-vscode#24]
Hi,

great stuff! Do you have a plan or do you know about any existing efforts to build the extension for IntelliJ?

I think it can be also made out of the existing project [https://github.com/codota/tabnine-intellij](https://github.com/codota/tabnine-intellij) similar to this repo. 

Thanks!

**Comment by JusttCallMeMike** [comment]
> Hi,
> 
> great stuff! Do you have a plan or do you know about any existing efforts to build the extension for IntelliJ?
> 
> I think it can be also made out of the existing project https://github.com/codota/tabnine-intellij similar to this repo.
> 
> Thanks!

Bro, You are a developer, this is free stuff, If you need this, just make it happen ;) and good luck!

**Comment by michaelfeil** [comment]
I agree, if we had a fork under https://github.com/huggingface, this would raise awareness.

**Comment by McPatate** [comment]
FYI this is one my todo list!
