### ISSUE TITLE
Developing Step 2: Install Deps failing

### ISSUE THREAD

**Issue by roblee-uk** [huggingface/llm-vscode#38]
Following the setup steps in the README I get as far as **Developing Step 2** 

I installed yarn, cloned the git repo and can cd into it. N.B. Not an experienced user of node.js / yarn. 

Have pasted the terminal readout having run 

> yarn install --frozen-lockfile

➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
➤ YN0000: ┌ Resolution step
➤ YN0061: │ vscode-test@npm:1.6.1 is deprecated: This package has been renamed to @vscode/test-electron, please update to the new name
➤ YN0061: │ vsce@npm:1.93.0 is deprecated: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
➤ YN0061: │ vscode-extension-telemetry@npm:0.1.7 is deprecated: This package has been renamed to @vscode/extension-telemetry, please update to the new name
➤ YN0061: │ vsce@npm:2.14.0 is deprecated: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
➤ YN0032: │ keytar@npm:7.9.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:4.3.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint (p6e2aa), requested by eslint-config-airbnb-base
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint (p32c28), requested by @typescript-eslint/parser
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint (p1d9db), requested by eslint-config-airbnb
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint-plugin-import (p4f5e3), requested by eslint-config-airbnb-base
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint-plugin-import (p98c99), requested by eslint-config-airbnb
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint-plugin-jsx-a11y (p220ec), requested by eslint-config-airbnb
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint-plugin-react (p92df3), requested by eslint-config-airbnb
➤ YN0002: │ eslint-config-airbnb-typescript@npm:12.3.1 doesn't provide eslint-plugin-react-hooks (pa6140), requested by eslint-config-airbnb
➤ YN0060: │ huggingface-vscode@workspace:. provides @typescript-eslint/parser (p3b6ed) with version 4.22.0, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ huggingface-vscode@workspace:. provides eslint (pd8c35) with version 8.28.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 13s 77ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed in 0s 209ms
➤ YN0000: Failed with errors in 13s 296ms

**Comment by yunfeilu92** [comment]
same error here

**Comment by McPatate** [comment]
The extension is undergoing a big refactoring, I'll mark this as closed for now. Let us know if you still have issues when trying to contribute.
