### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by vquilon** [huggingface/llm-vscode#42]
This may not be the place, but I would like to know if it would be possible to have some configuration about allowing data sharing, or at least inform that the model that is used or the API that is used is the one who manages these aspects.

On the other hand I would like to ask if anyone knows if bigcode somehow stores sent data because I have not found anything about this, only about the use of the model but not about the data used in the inference API used by this repository.

Thanks in advance.

**Comment by theonlyfoxy** [comment]
Is there any update on this? Huggingchat already have setting for "Share conversations with model authors".

**Comment by McPatate** [comment]
As of today all data sent to the Inference API is stored for debugging purposes / improving the product and checking for abuse. We do not use the data to train models nor do we sell it to anyone.

There's nothing much we can do on the client side to opt-out of this as long as it's not implemented in the Inference API. If you are concerned about your data being sent and stored on our servers, you will need to run your own server. The extension is compatible with [text-generation-inference](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate)'s API and [Inference API](https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task). If your http server complies with the previously mentioned APIs, you should be good to go.

More info here: https://huggingface.co/privacy
