### ISSUE TITLE
Sending input to the server only with a trigger key

### ISSUE THREAD

**Issue by melihgorgulu** [huggingface/llm-vscode#43]
As I understand every time I write a new line in vscode, huggingface extension send the code input to the server. But I want to send the input only when I pressed a specific key. So I want to set trigger key for huggingface model completion, I couldn't manage to find a configuration for this. Do you have this kind of feature ?

**Comment by McPatate** [comment]
Are you asking for a manual trigger (shortcut to ask for a completion) or an automatic trigger that activates when a certain set of characters are pressed?

**Comment by emnificent** [comment]
Personally, I would prefer the extension to remain inactive until I press a shortcut, asking for completion, that would also reduce the amount of API calls.

**Comment by McPatate** [comment]
I'm going to go ahead and assume that was asked in this PR was for a shortcut to trigger completions + the ability to disable ghost text.

Feel free to re-open a PR if that was not what you asked for.
