### ISSUE TITLE
Installing extension does not seem to work

### ISSUE THREAD

**Issue by henninglebbaeus** [huggingface/llm-vscode#44]
When I try to install the extension in VS Code, I only get the TabNine extension installed. Are there any steps to solve that?
I already tried to install manually from the VSIX file, but only get TabNine.

![image](https://github.com/huggingface/huggingface-vscode/assets/31338740/dde7bd0f-505e-4b36-abf3-a6b1435656aa)

VS Code version is 1.79.2

**Comment by VhaTer** [comment]
same on 
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
Work as henninglebbaeus suggest changing to 0.0.29

**Comment by McPatate** [comment]
Are you still having issues with new releases?

**Comment by henninglebbaeus** [comment]
> Are you still having issues with new releases?

No, new release installs smooth-as! 
Tried it today with version 0.1.0
