### ISSUE TITLE
Integrate LSP (Language Server Protocol) to improve suggestions

### ISSUE THREAD

**Issue by sansmoraxz** [huggingface/llm-vscode#45]
LSPs are spun up by most modern languages and IDEs.

So any way that can improve suggestions by taking the contexts from the language server such as the dependencies currently in the project can help filter out the suggestions. For example, suggesting fastapi when it's there in project dependency.

It can also help filter out junk suggestions through features, for example in case developers haven't explicitly declared a function with the types through LSP the model may be aware of it.

**Comment by McPatate** [comment]
I've just added [llm-ls](https://github.com/huggingface/llm-ls) to this project. Expect to see it in the next release!

There's still some work to do to support multi file context and context from dependencies, but it's on the roadmap.
