### ISSUE TITLE
Keyboard shortcut to trigger completion

### ISSUE THREAD

**Issue by Aloso** [huggingface/llm-vscode#48]
I'd like to trigger completion only when I press a certain keyboard shortcut. Could a configuration option for this be added?

**Comment by McPatate** [comment]
To make sure I understand, you'd like a shortcut to get a completion while disabling suggest-as-you-type suggestions?

**Comment by Aloso** [comment]
Yes, that would be best!

**Comment by McPatate** [comment]
The shortcut to get a completion will be available in the upcoming release, `cmd+shift+l` on mac (Trigger Inline Completion).

I'll take a look for disabling, shouldn't be to complicated

**Comment by McPatate** [comment]
FYI `0.1.0` is out
