### ISSUE TITLE
the vsix doesn't work?,how to fix it

### ISSUE THREAD

**Issue by CuteBadEgg** [huggingface/llm-vscode#50]
i download the vsix from https://marketplace.visualstudio.com/items?itemName=HuggingFace.huggingface-vscode&ssr=false#version-history，but in vscode when i installed it ,it doesn't work 。could you fix this?

**Comment by McPatate** [comment]
Could you explain in more detail what issue you're facing? Also, please include steps to reproduce.

**Comment by pzarzycki** [comment]
According to the documentation there should be an option "Llm: Config Template", but VS code shows only:
- LLm: "Login"
- Llm: "Logout"
- Llm: "Show Code attribution"
- Llm: "After Insert"

Login works, but nothing else is happening.

**Comment by McPatate** [comment]
@pzarzycki you are talking about commands while `Llm: Config Template` is a configuration setting, from the README:

> Open Vscode Settings (cmd+,) & type: Llm: Config Template

**Comment by pzarzycki** [comment]
Indeed, thank you. Somehow I miss that part.

**Comment by McPatate** [comment]
Closing, feel free to re-open if your problem persists.
