### ISSUE TITLE
Error 'HuggingFaceCode::setApiToken' not found in VSCode

### ISSUE THREAD

**Issue by Asterisk14** [huggingface/llm-vscode#53]
While Type: Hugging Face Code: Set API token in VSCode (Mac OS) getting
`Command 'Hugging Face Code: Set API token' resulted in an error (command 'HuggingFaceCode::setApiToken' not found)`

**Comment by agent-Y** [comment]
I ran it as described but got the same error.

**Comment by liujun5885** [comment]
got same error

**Comment by wmchurchill3** [comment]
I just ran into this.  
OS: Mac OS 13.5.2
VSCode: 1.82.0
HF Code Autocomplete: v0.0.38
I disabled Google Cloud Code, restarted VSCode, and was able to add my HF API key.
When I updated VSCode Duet AI (Google Cloud Code) had been enabled by default.  There seems to be an incompatibility between HF Code Autocomplete and Google Cloud Code.
Hope that helps!

**Comment by agent-Y** [comment]
@wmchurchill3 It worked fine! Thanks for the info!

**Comment by McPatate** [comment]
The login command will change in the upcoming release. Feel free to open another issue if the problem persists.
