### ISSUE TITLE
Getting results in C# and ASP.net core

### ISSUE THREAD

**Issue by moshere-ct** [huggingface/llm-vscode#56]
Hi,
I'm trying to use this extension for ASP.net core or C# languages.
However I'm keep getting results in Python.
Is there a way to configure it to specific language?

Thank you
Moshe

**Comment by McPatate** [comment]
This is dependant on the model you are using and not the extension. If you're using starcoder, afaik it should have no problem generating C#.

You can take a look at the other models presented in the configuration template as a starting point, or the [collection](https://huggingface.co/collections/mcpotato/code-completion-64feb4a720366846c3f52c39) I'll try maintaining.
