### ISSUE TITLE
I have deployed the codel-7b-instruct service locally, how do I use it in HF

### ISSUE THREAD

**Issue by bank010** [huggingface/llm-vscode#67]

**Comment by borzjyd62196** [comment]
I have the same problem

**Comment by McPatate** [comment]
You'll have to set the `modelIdOrEndpoint` configuration setting to the correct URL for your service.

Your model also has to be compatible with [text-generation-inference's API](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate) (available in the upcoming `0.0.39` release) or [Inference API's](https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task).

**Comment by McPatate** [comment]
Closing, feel free to re-open if the problem persists
