### ISSUE TITLE
Feature Request: Enable or disable the extension per file-extension

### ISSUE THREAD

**Issue by WissamAntoun** [huggingface/llm-vscode#68]
For people using Copilot and HuggingFace Code simultaneously, this is handy for people like me using HuggingFace code with a custom backend with Galactica to write .tex files, and Copilot for the rest.

My Custom Galactica repo for people interested: https://github.com/WissamAntoun/galactica-vscode-vllm

**Comment by McPatate** [comment]
Taking note, will see what we can do about it, though we have other more pressing priorities at the moment.

Feel free to attempt a fix yourself!
