### ISSUE TITLE
Unable to set API token

### ISSUE THREAD

**Issue by nwaokoron** [huggingface/llm-vscode#69]
I've tried run the command below but getting not found error for the command 

Cmd/Ctrl+Shift+P to open VSCode command palette
Type: Hugging Face Code: Set API token

**Comment by tcapelle** [comment]
Came for this

**Comment by McPatate** [comment]
The command for logging in will change in the upcoming release, feel free to open another issue if you're still experiencing difficulties.

**Comment by nwaokoron** [comment]
Thanks. Is there a set date for the next release?

**Comment by McPatate** [comment]
Should be pretty soon!
