### ISSUE TITLE
error trying to connect: invalid certificate: UnknownIssuer

### ISSUE THREAD

**Issue by ibicdev** [huggingface/llm-vscode#78]
I'm getting `error trying to connect: invalid certificate: UnknownIssuer` when llm-vscode is configured to use a self-hosted TGI endpoint.  Is there a way to disable certificate checking or take the environment variable `REQUESTS_CA_BUNDLE`?

**Comment by McPatate** [comment]
Did you try settings `llm.tlsSkipVerifyInsecure` setting?
<img width="323" alt="Screenshot 2023-09-28 at 10 40 19" src="https://github.com/huggingface/llm-vscode/assets/9112841/15e19c7d-7a76-4dad-b208-50bf98e0b54b">

**Comment by ibicdev** [comment]
Thanks @McPatate.  This solves the issue.

**Comment by PeterSulcs** [comment]
This "works" but would much rather it honored `NODE_EXTRA_CA_CERTS` or `REQUESTS_CA_BUNDLE` like most other node or Python tooling. This allows you to leave TLS verification on but check against an expanded set of known certs.

**Comment by McPatate** [comment]
The request isn't made by a node or python process. Feel free to open an issue or even better a PR in https://github.com/huggingface/llm-ls :)

**Comment by PeterSulcs** [comment]
@McPatate thanks for the prompt reply! Is it correct to say that the request to the model API happens in this language server (llm-ls), and specifically in Rust using the `reqwest` library?

**Comment by McPatate** [comment]
Yes correct!
