### ISSUE TITLE
Default request starcoder error：error decoding response body: expected value at line 1 column 1

### ISSUE THREAD

**Issue by mqbojee** [huggingface/llm-vscode#88]
<img width="481" alt="image" src="https://github.com/huggingface/llm-vscode/assets/24426579/2db57e68-51cc-4653-83a6-f464cb3b1cc8">

<img width="744" alt="image" src="https://github.com/huggingface/llm-vscode/assets/24426579/d053093d-d1ad-439d-8c48-fa041998247b">

**Comment by mqbojee** [comment]
Address "https://api-inference.huggingface.co/models/bigcode/starcoder"
There is a certificate issue and it doesn't seem to be responding properly, making the plugin unusable, please help me to see what's going on?

**Comment by McPatate** [comment]
That's odd, is there error still present? I haven't witnessed anything of the like today, I tried both llm.nvim & llm-vscode.

FYI, I'd advise not to skip the tls verification if you're not on a trusted network.
