### ISSUE TITLE
windows-specific path problems?

### ISSUE THREAD

**Issue by ArneRonneburg** [huggingface/llm-vscode#92]
When I try to use the extension with a custom code-completion server, I get the following error code. 
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. (os error 123) 
I am using a Windows OS, might that problem be related to this? How can I solve it?

**Comment by McPatate** [comment]
That's odd, I'm pretty sure I used platform agnostic path operators to generate paths in the extension.

**Comment by ArneRonneburg** [comment]
I verified that it's a windows issue...same settings, but Ubuntu VM, and everything is fine...

**Comment by McPatate** [comment]
Thanks for checking.

If someone wants to take a look, please do! I'll eventually come back to this when I have the time.

**Comment by Nicricflo** [comment]
I am getting the same error message (but in English).  I am specifically trying to load the LLM from a custom endpoint.

**Comment by Nicricflo** [comment]
@McPatate yes I am

**Comment by McPatate** [comment]
Ah, well for now consider it broken on windows, I have to investigate what's going on.

**Comment by McPatate** [comment]
@jklj077 ah yes that might totally be the issue here.
I'll fix that asap.

**Comment by VfBfoerst** [comment]
> I got the same error on Windows. I think it is related to this [line](https://github.com/huggingface/llm-ls/blob/4aacd7087ba1eab57eddd4f97dc5ae87c797a5e3/crates/llm-ls/src/main.rs#L506C1-L507C1). If using a custom endpoint and the tokenizer config is set to download from a Hugging Face repository, the code uses `model` (starting with http://... or https://...) instead of the `repository` to create a directory to store the tokenizer file, which will contain illegal characters (`:`) for Windows paths.
> 
> After setting the tokenizer config correctly following https://github.com/huggingface/llm-vscode#tokenizer (not the third one, ofc), this issue is now gone for me. However, I think it would be probably better to provide some tips in case misconfiguration.

I can confirm that. After setting to "null", the error is gone and the extension sends requests to my api (text-generation-inference container). It doesn't work as expected though (answers do not contain the wanted results) at the moment, but I can see autocompleted code in my workspace.

**Comment by RachelShalom** [comment]
Ihave the same issue on windows using startcoder costume endpoint. so I downloaded the tokenizer and added this to the settings:
`    "llm.tokenizer": {

        "path": "C:\\Users\\user_name\\Downloads\\tokenizer.json"

    },`
    
    and now I get the following error:
    error sending request for url (https://3.219.17.118:8000/generate): error trying to connect: received corrupt message of type InvalidContentType

**Comment by McPatate** [comment]
@RachelShalom this seems unrelated, please open an new issue.

**Comment by darolt** [comment]
I am having the same problem here. It works perfectly on Linux (Ubuntu), but not working on Windows (I got the same error message). I'm on v0.1.6.

**Comment by darolt** [comment]
I added the tokenizer as a local file as @RachelShalom did. It seems to have avoided this particular bug, but it uncovered another bug that only happens on Windows:
`error sending request for url (my endpoint url here): error trying to connect: invalid peer certificate: UnknownIssuer.`

Again, the same token and config works on Ubuntu.

**Comment by r5r3** [comment]
Same Problem here with custom endpoint and extension version v0.1.6. On Linux and macOS it works perfectly, on Windows I get `(os error 123)`

**Comment by McPatate** [comment]
The issue should be fixed in `0.5.x`, can someone confirm it's working now?

**Comment by r5r3** [comment]
For me, this error is solved. Thanks a lot!
