### ISSUE TITLE
Getting Input validation error

### ISSUE THREAD

**Issue by cmosguy** [huggingface/llm-vscode#94]
Keep getting this error message when the `llm-vscode` extension is running.

```
Input validation error: `inputs` tokens + `max_new_tokens` must be <= 2048. Given: 3474 `inputs` tokens and 60 `max_new_tokens`
```

**Comment by McPatate** [comment]
What did you set the context window to?

**Comment by cmosguy** [comment]
I set the context window to 8096 or something like that... I guess I have to set to smaller amount - like `2048` or should I set it to `2048-60`?

**Comment by McPatate** [comment]
It depends on the model, check the context window of the model. But yes generally it should be set to `context_window - max_new_tokens`

**Comment by McPatate** [comment]
Closing for now, feel free to re-open if you're still facing an issue

**Comment by hossamrizk** [comment]
Any updates?
